### ISSUE TITLE
README.md missing instructions on installing R tutorial dependencies

### ISSUE THREAD

**Issue by btiernay** [datalayer/datalayer-zeppelin#6]
It appears as though the instructions here:

https://github.com/datalayer/datalayer-zeppelin#get-the-image-from-the-docker-repository

Are not sufficient to run the `R Tutorial` when the container is up. Additional work is required:

```shell
docker run -it -p 2222:22 -p 8080:8080 -p 4040:4040 datalayer/zeppelin-rscala
docker exec -it $(docker ps -lq) bash
yum -y install libcurl-devel openssl-devel
R -e "install.packages(c('devtools','mplot', 'googleVis'), repos = 'http://cran.us.r-project.org'); require(devtools); install_github('ramnathv/rCharts')"
```

I have verified that the above works for the `latest` `datalayer/zeppelin-rscala` docker image.

**Comment by btiernay** [comment]
Thanks @echarles! You may also want to fix https://github.com/datalayer/datalayer-zeppelin#prerequisite   as one of the instructions is missing quotes:

```shell
R -e install.packages('knitr', repos = 'http://cran.us.r-project.org')
```

**Comment by echarles** [comment]
@btiernay Thx for contributing. I have just pushed a new docker image with the latest changes on https://hub.docker.com/r/datalayer/zeppelin-rscala/
